language: haskell

ghc: 7.8

before_install:
 - sudo add-apt-repository ppa:mystic-mirage/opentracker -y
 - sudo apt-get update -q
 - sudo apt-get install opentracker opentracker-ipv6
 - cabal install --only-dependencies --enable-tests --enable-library-coverage

install:
 - cabal configure --enable-tests
 - cabal build

script:
 - ./dist/build/test/test && ./dist/build/doctests/doctests

after_script:
 - cabal install hpc-coveralls
 - hpc-coveralls test doctests
