language: haskell

env:
 - GHCVER=7.8.3

before_install:
 - cabal install --only-dependencies --enable-tests

install:
 - cabal configure --enable-tests
 - cabal build

script:
 - ./dist/build/test/test && ./dist/build/doctests/doctests
